//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.default_TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerAnalog
        {
            get
            {
                return SteamVR_Actions.default_TriggerAnalog;
            }
        }
        
        public virtual SteamVR_Action_Boolean AButton
        {
            get
            {
                return SteamVR_Actions.default_AButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean BButton
        {
            get
            {
                return SteamVR_Actions.default_BButton;
            }
        }
        
        public virtual SteamVR_Action_Pose HandGripPose
        {
            get
            {
                return SteamVR_Actions.default_HandGripPose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeft
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeft;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRight
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
